repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.1'
    hooks:
    -   id: mypy
        additional_dependencies: [
            "django-stubs",
            "djangorestframework-stubs",
            "mypy-django-plugin"
        ]

-   repo: local
    hooks:
    -   id: django-migrations-check
        name: Django migrations check
        entry: python manage.py makemigrations --check --dry-run
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]