FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.lock /app/
COPY requirements-dev.lock /app/

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /app/requirements.lock
RUN pip install --no-cache-dir -r /app/requirements-dev.lock

COPY manage.py /app/
COPY pyproject.toml /app/
COPY api /app/api
COPY core /app/core
COPY dashboard /app/dashboard
COPY orders /app/orders
COPY payments /app/payments
COPY pizza_project /app/pizza_project
COPY products /app/products
COPY users /app/users

COPY ./entrypoint.sh /app/entrypoint.sh
COPY ./entrypoint-celery.sh /app/entrypoint-celery.sh
RUN chmod +x /app/entrypoint.sh
RUN chmod +x /app/entrypoint-celery.sh

ENTRYPOINT ["/app/entrypoint.sh"]

EXPOSE 8000