FROM node:20-alpine as build-stage
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend .
RUN npm run build

FROM nginx:1.21.6-alpine
RUN apk add --no-cache gettext
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.prod.conf /etc/nginx/conf.d/nginx.prod.conf
COPY ./nginx/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80 443
CMD ["/entrypoint.sh"]