# Generated by Django 5.2.6 on 2025-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Вопрос и ответ (FAQ)",
                "verbose_name_plural": "Вопросы и ответы (FAQ)",
                "ordering": ["order"],
            },
        ),
    ]
