# Generated by Django 5.2.6 on 2025-09-19 14:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecipeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название категории"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recipe_category_icons/",
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория рецепта",
                "verbose_name_plural": "Категории рецептов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecipeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название тега"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Тег рецепта",
                "verbose_name_plural": "Теги рецептов",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название рецепта"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Короткое описание для списка рецептов",
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        help_text="Подробное пошаговое описание приготовления",
                        verbose_name="Полное описание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="recipes/", verbose_name="Изображение рецепта"
                    ),
                ),
                (
                    "prep_time",
                    models.PositiveIntegerField(verbose_name="Время подготовки (мин)"),
                ),
                (
                    "cook_time",
                    models.PositiveIntegerField(
                        verbose_name="Время приготовления (мин)"
                    ),
                ),
                (
                    "servings",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество порций",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Легкий"),
                            ("MEDIUM", "Средний"),
                            ("HARD", "Сложный"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipes",
                        to="recipes.recipecategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipes",
                        to="recipes.recipetag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["difficulty"], name="recipes_rec_difficu_33131c_idx"
                    ),
                    models.Index(
                        fields=["category"], name="recipes_rec_categor_4c01e4_idx"
                    ),
                ],
            },
        ),
    ]
